# Generated by Django 4.1.4 on 2022-12-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('procedencia', models.CharField(max_length=100)),
                ('ingredientes', models.IntegerField()),
            ],
        ),
    ]
